### ISSUE TITLE
It will be really interesting if you can provide a reverse switch as well. Only to keep the elements with x-internal: true.

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Mermade/openapi-filter#1]
It will be really interesting if you can provide a reverse switch as well. Only to keep the elements with x-internal: true. Useful for a quick check around what's getting filtered out.

**Comment by MikeRalphson** [comment]
I think that should be do-able!

**Comment by MikeRalphson** [comment]
v1.1.0 has a new `--inverse` switch/option.

Filtered elements are shown with enough structural properties to show the path to the removed elements, e.g. in this example:

```yaml
info:
  x-logo:
    url: 'http://imgs.xkcd.com/static/terrible_small_logo.png'
    x-internal: true
```

Means the `x-logo` object has been removed from the `info` object, but not necessarily that the whole of the `info` object has been removed.

Of course, the output of filtered properties won't necessarily be a valid OpenAPI/etc definition.

Thanks for the suggestion!

**Comment by shreyas-agnihotri** [comment]
That was quick! :-) Thanks again..
