### ISSUE TITLE
OpenAPI v3.1 support

### ISSUE THREAD

**Issue by philsturgeon** [Mermade/openapi-filter#132]
I'm guessing this package probably supports OpenAPI v3.1 ok as the changes being made are not too valid to the overall way this works, but I wanted to double check.

I want to update [openapi.tools](https://openapi.tools) if so.

**Comment by MikeRalphson** [comment]
Sorry for neglecting my issues. Yes, OpenAPI 3.1 should work just fine.

**Comment by philsturgeon** [comment]
Nice one Mike! I've just updated OpenAPI.Tools.
