### ISSUE TITLE
--valid not keeping entire info section

### ISSUE THREAD

**Issue by StephenNay** [Mermade/openapi-filter#16]
This nifty tool could save me some headaches, so I really appreciate your effort in making it. I need to produce three or four flavors of an API spec, so it's easier for me to tag operations with what flavor they should be in rather than what flavors they should be filtered out of. Consequently, I'm trying to use the -inverse option. I quickly discovered that I also need to use the --valid option, which put the openapi and info sections at the bottom of the output file. 

I have a suggestion and bug report:

Suggestion: I know that putting those sections at the bottom of the file results in a valid OpenAPI file, but people are used to seeing them at the beginning of the file. Any chance you can put them at the top of the output for people who open the file in a text editor?

Bug: The info section in my source file contains title, version, and description, but the output from openapi-filter only contains title and version. The description should also be included in the output.

Also, I just noticed that the version value is being truncated if it ends in .0. In my source file it's 3.0, and in the output of openapi-filter it's just 3.

**Comment by MikeRalphson** [comment]
> Suggestion: I know that putting those sections at the bottom of the file results in a valid OpenAPI file, but people are used to seeing them at the beginning of the file. Any chance you can put them at the top of the output for people who open the file in a text editor?

Done.

> Bug: The info section in my source file contains title, version, and description, but the output from openapi-filter only contains title and version. The description should also be included in the output.

Not a bug, as `description` is not a mandatory property of the `info` object. I have however added a `--info` option to include the full, not a minimal `info` object in the output.

> Also, I just noticed that the version value is being truncated if it ends in .0. In my source file it's 3.0, and in the output of openapi-filter it's just 3.

Also likely not a bug, I'm guessing you aren't quoting the value `3.0` which means it is being interpreted as a number, and re-output as an integer. If you add quotes to your input file value or make it unambiguously a string, such as `3.0.0` then this should not happen.
