### ISSUE TITLE
--strip option not recognized

### ISSUE THREAD

**Issue by StephenNay** [Mermade/openapi-filter#17]
I tried using the --strip option to remove tags after filtering, but that just caused openapi-filter to show the usage information, and to say that strip is an unknown argument. Same with -s.

**Comment by MikeRalphson** [comment]
Looking at the commits and tags I don't think the `--strip` option enhancement has been released yet. Will close this when done.

**Comment by MikeRalphson** [comment]
Version `1.4.0` published,
