### ISSUE TITLE
Enhancement: Instead of hardcoding the name of vendor extension 'x-internal' will it be possible to optionally accept the list of extensions to filter out as user input?

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Mermade/openapi-filter#2]
Default can remain 'x-internal' but also allow users to specify a list of custom vendor extensions (such ['x-private', 'x-hidden', 'x-do-not-show'] etc.) on command line, based on which ```openapi-filter``` can filter out the elements.

**Comment by MikeRalphson** [comment]
Version 1.2.0 has a `--tags` option for this. Thanks again for the suggestion!

**Comment by shreyas-agnihotri** [comment]
Many thanks! You are awesome.
