### ISSUE TITLE
execution failes from 1.4.0

### ISSUE THREAD

**Issue by fehmer** [Mermade/openapi-filter#21]
After update yargs from 10.x to 14.x  calling `openapi-filter --tags x-public x-hidden -- infile.yaml`  fails with
```
Usage: openapi-filter [options] {infile} [{outfile}]

Options:
---snip---

Not enough non-option arguments: got 0, need at least 1
```

**Comment by pineman** [comment]
Also seeing this. yargs v.15.0.2, openapi-filter 1.4.0

**Comment by MikeRalphson** [comment]
Thanks, that's what I was going to try next!

**Comment by MikeRalphson** [comment]
Yargs seems to have got more opionated lately, and seems to have broken some stuff in the 14.x minor releases. Reworked.

**Comment by pineman** [comment]
@MikeRalphson Thank you so much. Will this be included in a new release soon?

**Comment by MikeRalphson** [comment]
v1.5.0 has just been released.
