### ISSUE TITLE
Documentation: Provide command-line example for usage of tags

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Mermade/openapi-filter#3]
Due to the way `yargs` handles array parameters (https://github.com/yargs/yargs/issues/162), the command-line below fails:

`node openapi-filter --tags x-internal x-hidden swagger.yaml filtered.yaml`

But this works:
`node openapi-filter --tags x-internal x-hidden -- swagger.yaml filtered.yaml`

Might want to update the readme with an example, so that other users don't trip over this.

**Comment by MikeRalphson** [comment]
PR? :smiley:

**Comment by shreyas-agnihotri** [comment]
My employer has a strict policy around public contributions while I am employed. Else I would be more than happy to..

**Comment by MikeRalphson** [comment]
Oh, that's a shame. No worries, will amend the README.md

**Comment by MikeRalphson** [comment]
Updated. Thanks.
