### ISSUE TITLE
Output when using the inverse option should be valid

### ISSUE THREAD

**Issue by ian-rose** [Mermade/openapi-filter#7]
I am using the `--inverse` option to output both external and internal API documentation. When I output the external documentation everything works as expected, however when I run openapi-filter with the `--inverse` option the output is not a validOpenAPI object. Because of this I cannot run it through a documentation generator to output human-readable documentation.

Per https://github.com/Mermade/openapi-filter/issues/1#issuecomment-352451287 this is a known issue. I believe there is an easy fix for the 90% use case: the `openapi` and `info` fields are required in the OpenAPI object, so these fields should always be included in the output of openapi-filter.

**Comment by MikeRalphson** [comment]
As per #1 this wasn't really the intended use case of the `--inverse` option, that was to be able to see what was being filtered out.

However, I can see an additional option being useful for the use-case you describe.

**Comment by MikeRalphson** [comment]
`--valid` option added in `v1.3.0`.
