### ISSUE TITLE
PR Idea - pass options as file

### ISSUE THREAD

**Issue by thim81** [Mermade/openapi-filter#72]
Right now the options have to be passed as arguments to the CLI.

This works fine for when you have a limited set of options to set, but if you want to filter out a large number of methods/operationIds, it would make more sense to provide a "options" file as a parameter.

something like `--optionsFile ./config/openapi-filter-options.json`

Which would results in

`openapi-filter source.yaml target.yaml --optionsFile ./config/openapi-filter-options.json`

Do you have a suggestion how the openapi-filter-options.json should be structured?

**Comment by MikeRalphson** [comment]
#73 has been merged.
